import { useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'language';
const LANGUAGE_EVENT = 'unievent-language-change';

const dictionaries = {
  pt: {
    navHome: 'Home',
    navInstitutions: 'Instituições',
    navSecretarias: 'Secretarias',
    navEvents: 'Eventos',
    navPeople: 'Pessoas',
    navCertificates: 'Certificados',
    navSupport: 'Suporte',
    back: 'Voltar',
    logout: 'Sair',
    login: 'Login',
    themeLight: 'Modo claro',
    themeDark: 'Modo escuro',
    activateLight: 'Ativar modo claro',
    activateDark: 'Ativar modo escuro',
    language: 'Idioma',
    portuguese: 'Português',
    english: 'English',

    navigationPublic: 'Navegação principal',
    openMenu: 'Abrir menu',
    closeMenu: 'Fechar menu',
    myTickets: 'Meus ingressos',
    publicLogin: 'Entrar',
    secretaryRegistration: 'Cadastro Secretaria',
    landingAbout: 'Sobre',
    landingApp: 'Aplicativo',
    landingMembers: 'Integrantes',
    landingContact: 'Contato',
    landingEyebrow: 'Eventos universitarios em um so lugar',
    landingTitle: 'Descubra, conecte e participe com o UniEvent.',
    landingCopy: 'Uma plataforma para organizar eventos institucionais, aproximar alunos da comunidade academica e transformar a divulgacao de atividades em uma experiencia simples, visual e acessivel.',
    landingPrimary: 'Ver aplicativo',
    landingSecondary: 'Falar conosco',
    landingHighlights: 'Destaques',
    landingEventsTitle: 'Eventos',
    landingEventsDesc: 'cadastro, detalhes e visualizacao',
    landingCommunityTitle: 'Comunidade',
    landingCommunityDesc: 'integracao entre alunos e instituicao',
    landingManagementTitle: 'Gestao',
    landingManagementDesc: 'fluxo pensado para organizadores',
    landingScreens: 'Telas principais',
    landingTeam: 'Equipe',
    landingTeamTitle: 'Integrantes',
    landingContactCopy: 'Ideias, duvidas ou sugestoes para evoluir o UniEvent.',
    contactUs: 'Contate-nos',
    fullName: 'Seu nome completo',
    email: 'Seu email',
    message: 'Mensagem',
    enterName: 'Digite seu nome',
    enterEmail: 'Digite seu email',
    enterMessage: 'Digite sua mensagem',
    send: 'Enviar',
    integratorProject: 'Projeto Integrador',

    authBack: 'Voltar para a landing page',
    authAdmin: 'Admin',
    authIntroSignUp: 'Crie sua conta para gerenciar eventos.',
    authIntroSignIn: 'Entre para acompanhar seus eventos.',
    authCopy: 'Acesse um painel pensado para instituicoes, organizadores e equipes que precisam publicar, revisar e acompanhar eventos academicos com clareza.',
    authBenefit1: 'Cadastro rapido de eventos',
    authBenefit2: 'Fluxo visual para organizadores',
    authBenefit3: 'Experiencia clara em qualquer tema',
    signup: 'Cadastro',
    signin: 'Login',
    createAccount: 'Criar conta',
    welcomeBack: 'Bem-vindo de volta',
    authSwitch: 'Alternar entre login e cadastro',
    enter: 'Entrar',
    register: 'Cadastrar',
    fullNameShort: 'Nome completo',
    institutionalEmail: 'Email institucional',
    password: 'Senha',
    confirmPassword: 'Confirmar senha',
    enterPassword: 'Digite sua senha',
    confirmPasswordPlaceholder: 'Confirme sua senha',
    forgotPassword: 'Esqueci minha senha',
    signupConfirmationSent: 'Cadastro criado. Enviamos um email de confirmacao para o endereco informado. Confirme o email antes de fazer login.',
    signupCreatedEmailFailed: 'Cadastro criado, mas nao foi possivel enviar o email de confirmacao.',
    signupCreatedEmailRetry: 'Verifique a configuracao de email da API e tente reenviar a confirmacao.',
    resendConfirmationEmail: 'Reenviar email de confirmacao',
    resendingConfirmationEmail: 'Reenviando...',
    confirmEmailTitle: 'Confirmacao de email',
    confirmEmailPendingApi: 'Recebemos sua chave de confirmacao. Para liberar o login automaticamente, conecte esta tela ao endpoint de confirmacao da API.',
    confirmEmailMissingKey: 'O link de confirmacao nao possui uma chave valida. Solicite um novo email de confirmacao.',
    confirmEmailLoginButton: 'Ir para o login',

    adminGreeting: 'Olá, Administrador',
    dashboardEyebrow: 'Painel administrativo',
    dashboardTitle: 'Gerencie a experiencia UniEvent com praticidade.',
    dashboardCopy: 'Escolha uma acao para criar, acompanhar e organizar eventos academicos.',
    dashboardEventsDesc: 'cadastro e gestao',
    dashboardModules: '5 modulos',
    dashboardModulesDesc: 'atalhos principais',
    dashboardSupportDesc: 'ajuda disponivel',
    quickActions: 'Acoes rapidas',
    quickActionsCopy: 'Acesse as tarefas mais usadas do painel.',
    createEvent: 'Criar Evento',
    createEventDesc: 'Cadastre uma nova atividade',
    manageEvents: 'Gerenciar Eventos',
    manageEventsDesc: 'Edite e acompanhe eventos',
    managePeople: 'Gerenciar Pessoas',
    managePeopleDesc: 'Organize perfis e acessos',
    createResponsible: 'Criar Responsável',
    createResponsibleDesc: 'Adicione novos organizadores',
    manageCertificates: 'Gerenciar Certificados',
    manageCertificatesDesc: 'Controle emissao e validacao',

    eventsListTitle: 'Listagem de Eventos',
    eventsRegistered: 'Eventos cadastrados',
    eventsHeading: 'Listagem de eventos',
    eventsCopy: 'Consulte, edite e acompanhe os eventos publicados no UniEvent.',
    newEvent: 'Novo evento',
    eventsSummary: 'Resumo de eventos',
    events: 'Eventos',
    capacity: 'Capacidade',
    categories: 'Categorias',
    results: 'Resultados',
    allEvents: 'Todos os eventos',
    recordsFound: '{count} registro(s) encontrado(s)',
    searchEvent: 'Buscar evento',
    noEvents: 'Nenhum evento encontrado',
    title: 'Título',
    responsible: 'Responsável',
    eventType: 'Tipo de Evento',
    date: 'Data',
    time: 'Hora',
    image: 'Imagem',
    description: 'Descrição',
    actions: 'Ações',
    edit: 'Editar',
    delete: 'Excluir',
    preview: 'Visualizar Preview',
    deleteEventTitle: 'Excluir evento',
    deleteEventMessage: 'Tem certeza que deseja excluir este evento?',

    updateEvent: 'Atualizar Evento',
    eventUpdated: 'Evento atualizado com sucesso.',
    eventCreated: 'Evento criado com sucesso.',
    editRegistration: 'Editar cadastro',
    eventEditorNew: 'Novo evento',
    eventEditorTitleEdit: 'Atualize as informacoes do evento.',
    eventEditorTitleCreate: 'Cadastre uma nova experiencia academica.',
    eventEditorCopy: 'Preencha os dados principais, escolha o responsavel e adicione uma imagem para destacar o evento no aplicativo.',
    formSummary: 'Resumo do formulario',
    dateAndTime: 'Data e horario',
    eventImage: 'Imagem do evento',
    form: 'Formulario',
    eventData: 'Dados do evento',
    eventDetails: 'Detalhes do evento',
    reviewBeforeSave: 'Revise as informacoes antes de salvar.',
    fieldsAppear: 'Os campos abaixo aparecem na listagem e no preview.',
    ok: 'Ok',
    selectResponsible: 'Selecione um responsável',
    maxPeople: 'N° máximo de pessoas',

    peopleTeam: 'Equipe UniEvent',
    peopleCopy: 'Consulte responsáveis cadastrados, acompanhe perfis e adicione novos organizadores.',
    newResponsible: 'Novo responsável',
    peopleSummary: 'Resumo de pessoas',
    people: 'Pessoas',
    registeredResponsible: 'Responsáveis cadastrados',
    searchPerson: 'Buscar pessoa',
    responsibleLabel: 'Responsável',
    personLinked: 'Pessoa vinculada a organização de eventos.',
    editResponsible: 'Editar responsável',
    deleteResponsible: 'Excluir responsável',
    noPeople: 'Nenhuma pessoa encontrada.',
    deleteResponsibleTitle: 'Excluir responsável',
    deleteResponsibleMessage: 'Tem certeza que deseja remover esta pessoa?',
    responsibleNewEyebrow: 'Novo responsável',
    responsibleNewTitle: 'Cadastre pessoas para organizar eventos.',
    responsibleNewCopy: 'Adicione responsáveis ao painel para associar eventos, facilitar a gestão e manter a equipe organizada.',
    accessProfile: 'Perfil de acesso',
    organizerTeam: 'Equipe organizadora',
    responsibleForEvents: 'Responsável por eventos',
    responsibleData: 'Dados do responsável',
    responsibleHint: 'Use uma foto simples e um nome claro para identificar a pessoa nas telas do painel.',
    responsibleName: 'Nome Responsável',
    profilePhoto: 'Foto de Perfil',
    responsiblePreviewAlt: 'Prévia do responsável',
    changePhoto: 'Alterar foto',
    responsibleCreated: 'Responsável criado com sucesso.',

    certificatesUniEvent: 'Certificados UniEvent',
    certificatesCopy: 'Controle os certificados emitidos para alunos vinculados aos eventos cadastrados.',
    newCertificate: 'Novo certificado',
    certificatesSummary: 'Resumo de certificados',
    certificates: 'Certificados',
    certificatesIssued: 'Certificados emitidos',
    searchCertificate: 'Buscar certificado',
    certificate: 'Certificado',
    eventId: 'Evento ID',
    studentId: 'Aluno ID',
    noCertificates: 'Nenhum certificado encontrado.',
    deleteCertificateTitle: 'Excluir certificado',
    deleteCertificateMessage: 'Tem certeza que deseja remover este certificado?',
    createCertificate: 'Criar Certificado',
    certificateCreated: 'Certificado criado com sucesso.',
    certificateNewEyebrow: 'Novo certificado',
    certificateNewTitle: 'Emita certificados para alunos vinculados a eventos.',
    certificateNewCopy: 'Use esta tela para registrar certificados de eventos que possuem emissão habilitada no UniEvent.',
    certificateFields: 'Campos do certificado',
    certificateDate: 'Data certificado',
    certificateData: 'Dados do certificado',
    certificateHint: 'Informe o evento, o aluno e o texto que será apresentado no certificado.',
    selectEvent: 'Selecione um evento',
    certificateTextPlaceholder: 'Digite o texto do certificado',
    certificatePreview: 'Prévia do certificado',
    eventNotSelected: 'Evento ainda não selecionado',
    certificateTextFallback: 'O texto informado será exibido aqui.',

    supportTitle: 'Suporte',
    lightMode: 'Modo Claro',

    previewTitle: 'Preview',
    organizer: 'Organizador',
    learnMore: 'Saiba Mais',
    aboutEvent: 'Sobre o evento',
    previewCopy: 'Nosso tão esperado TeckRock acontece amanhã aqui na unidade. Um show incrível de rock com a banda formada por alunos dos cursos de GPI, ADS e GE. Entrada gratuita, com arrecadação solidária de produtos de higiene.',
    getTicket: 'GARANTIR INGRESSO',
    notFound: 'Página não encontrada',
    backHome: 'Voltar ao início',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    tableEmpty: 'Nenhum registro encontrado',
    navigationAdmin: 'Navegação administrativa',
    categoryLecture: 'Palestra',
    categoryMusic: 'Música',
    categoryWorkshop: 'Workshop',
    categoryTechnology: 'Tecnologia',
    categoryCultural: 'Cultural',
  },
  en: {
    navHome: 'Home',
    navInstitutions: 'Institutions',
    navSecretarias: 'Secretaries',
    navEvents: 'Events',
    navPeople: 'People',
    navCertificates: 'Certificates',
    navSupport: 'Support',
    back: 'Back',
    logout: 'Log out',
    login: 'Login',
    themeLight: 'Light mode',
    themeDark: 'Dark mode',
    activateLight: 'Enable light mode',
    activateDark: 'Enable dark mode',
    language: 'Language',
    portuguese: 'Portuguese',
    english: 'English',

    navigationPublic: 'Main navigation',
    openMenu: 'Open menu',
    closeMenu: 'Close menu',
    myTickets: 'My tickets',
    publicLogin: 'Sign in',
    secretaryRegistration: 'Secretary registration',
    landingAbout: 'About',
    landingApp: 'App',
    landingMembers: 'Team',
    landingContact: 'Contact',
    landingEyebrow: 'University events in one place',
    landingTitle: 'Discover, connect, and join with UniEvent.',
    landingCopy: 'A platform to organize institutional events, connect students with the academic community, and make activity promotion simple, visual, and accessible.',
    landingPrimary: 'View app',
    landingSecondary: 'Contact us',
    landingHighlights: 'Highlights',
    landingEventsTitle: 'Events',
    landingEventsDesc: 'registration, details, and viewing',
    landingCommunityTitle: 'Community',
    landingCommunityDesc: 'connection between students and institution',
    landingManagementTitle: 'Management',
    landingManagementDesc: 'workflow designed for organizers',
    landingScreens: 'Main screens',
    landingTeam: 'Team',
    landingTeamTitle: 'Members',
    landingContactCopy: 'Ideas, questions, or suggestions to improve UniEvent.',
    contactUs: 'Contact us',
    fullName: 'Your full name',
    email: 'Your email',
    message: 'Message',
    enterName: 'Enter your name',
    enterEmail: 'Enter your email',
    enterMessage: 'Enter your message',
    send: 'Send',
    integratorProject: 'Integrator Project',

    authBack: 'Back to landing page',
    authAdmin: 'Admin',
    authIntroSignUp: 'Create your account to manage events.',
    authIntroSignIn: 'Sign in to track your events.',
    authCopy: 'Access a dashboard designed for institutions, organizers, and teams that need to publish, review, and manage academic events clearly.',
    authBenefit1: 'Fast event registration',
    authBenefit2: 'Visual workflow for organizers',
    authBenefit3: 'Clear experience in any theme',
    signup: 'Sign up',
    signin: 'Login',
    createAccount: 'Create account',
    welcomeBack: 'Welcome back',
    authSwitch: 'Switch between login and sign up',
    enter: 'Sign in',
    register: 'Sign up',
    fullNameShort: 'Full name',
    institutionalEmail: 'Institutional email',
    password: 'Password',
    confirmPassword: 'Confirm password',
    enterPassword: 'Enter your password',
    confirmPasswordPlaceholder: 'Confirm your password',
    forgotPassword: 'Forgot my password',
    signupConfirmationSent: 'Account created. We sent a confirmation email to the provided address. Confirm your email before signing in.',
    signupCreatedEmailFailed: 'Account created, but we could not send the confirmation email.',
    signupCreatedEmailRetry: 'Check the API email settings and try resending the confirmation.',
    resendConfirmationEmail: 'Resend confirmation email',
    resendingConfirmationEmail: 'Resending...',
    confirmEmailTitle: 'Email confirmation',
    confirmEmailPendingApi: 'We received your confirmation key. To unlock sign-in automatically, connect this screen to the API confirmation endpoint.',
    confirmEmailMissingKey: 'This confirmation link does not include a valid key. Request a new confirmation email.',
    confirmEmailLoginButton: 'Go to login',

    adminGreeting: 'Hello, Administrator',
    dashboardEyebrow: 'Admin dashboard',
    dashboardTitle: 'Manage the UniEvent experience with ease.',
    dashboardCopy: 'Choose an action to create, track, and organize academic events.',
    dashboardEventsDesc: 'registration and management',
    dashboardModules: '5 modules',
    dashboardModulesDesc: 'main shortcuts',
    dashboardSupportDesc: 'help available',
    quickActions: 'Quick actions',
    quickActionsCopy: 'Access the dashboard tasks used most often.',
    createEvent: 'Create Event',
    createEventDesc: 'Register a new activity',
    manageEvents: 'Manage Events',
    manageEventsDesc: 'Edit and track events',
    managePeople: 'Manage People',
    managePeopleDesc: 'Organize profiles and access',
    createResponsible: 'Create Responsible',
    createResponsibleDesc: 'Add new organizers',
    manageCertificates: 'Manage Certificates',
    manageCertificatesDesc: 'Control issuing and validation',

    eventsListTitle: 'Event Listing',
    eventsRegistered: 'Registered events',
    eventsHeading: 'Event listing',
    eventsCopy: 'View, edit, and track events published on UniEvent.',
    newEvent: 'New event',
    eventsSummary: 'Events summary',
    events: 'Events',
    capacity: 'Capacity',
    categories: 'Categories',
    results: 'Results',
    allEvents: 'All events',
    recordsFound: '{count} record(s) found',
    searchEvent: 'Search event',
    noEvents: 'No events found',
    title: 'Title',
    responsible: 'Responsible',
    eventType: 'Event Type',
    date: 'Date',
    time: 'Time',
    image: 'Image',
    description: 'Description',
    actions: 'Actions',
    edit: 'Edit',
    delete: 'Delete',
    preview: 'View Preview',
    deleteEventTitle: 'Delete event',
    deleteEventMessage: 'Are you sure you want to delete this event?',

    updateEvent: 'Update Event',
    eventUpdated: 'Event updated successfully.',
    eventCreated: 'Event created successfully.',
    editRegistration: 'Edit registration',
    eventEditorNew: 'New event',
    eventEditorTitleEdit: 'Update the event information.',
    eventEditorTitleCreate: 'Register a new academic experience.',
    eventEditorCopy: 'Fill in the main details, choose the responsible person, and add an image to highlight the event in the app.',
    formSummary: 'Form summary',
    dateAndTime: 'Date and time',
    eventImage: 'Event image',
    form: 'Form',
    eventData: 'Event data',
    eventDetails: 'Event details',
    reviewBeforeSave: 'Review the information before saving.',
    fieldsAppear: 'The fields below appear in the listing and preview.',
    ok: 'Ok',
    selectResponsible: 'Select a responsible person',
    maxPeople: 'Max number of people',

    peopleTeam: 'UniEvent Team',
    peopleCopy: 'View registered responsible people, track profiles, and add new organizers.',
    newResponsible: 'New responsible',
    peopleSummary: 'People summary',
    people: 'People',
    registeredResponsible: 'Registered responsible people',
    searchPerson: 'Search person',
    responsibleLabel: 'Responsible',
    personLinked: 'Person linked to event organization.',
    editResponsible: 'Edit responsible',
    deleteResponsible: 'Delete responsible',
    noPeople: 'No people found.',
    deleteResponsibleTitle: 'Delete responsible',
    deleteResponsibleMessage: 'Are you sure you want to remove this person?',
    responsibleNewEyebrow: 'New responsible',
    responsibleNewTitle: 'Register people to organize events.',
    responsibleNewCopy: 'Add responsible people to the dashboard to link events, simplify management, and keep the team organized.',
    accessProfile: 'Access profile',
    organizerTeam: 'Organizer team',
    responsibleForEvents: 'Responsible for events',
    responsibleData: 'Responsible data',
    responsibleHint: 'Use a simple photo and a clear name to identify the person in dashboard screens.',
    responsibleName: 'Responsible Name',
    profilePhoto: 'Profile Photo',
    responsiblePreviewAlt: 'Responsible preview',
    changePhoto: 'Change photo',
    responsibleCreated: 'Responsible created successfully.',

    certificatesUniEvent: 'UniEvent Certificates',
    certificatesCopy: 'Control certificates issued to students linked to registered events.',
    newCertificate: 'New certificate',
    certificatesSummary: 'Certificates summary',
    certificates: 'Certificates',
    certificatesIssued: 'Issued certificates',
    searchCertificate: 'Search certificate',
    certificate: 'Certificate',
    eventId: 'Event ID',
    studentId: 'Student ID',
    noCertificates: 'No certificates found.',
    deleteCertificateTitle: 'Delete certificate',
    deleteCertificateMessage: 'Are you sure you want to remove this certificate?',
    createCertificate: 'Create Certificate',
    certificateCreated: 'Certificate created successfully.',
    certificateNewEyebrow: 'New certificate',
    certificateNewTitle: 'Issue certificates for students linked to events.',
    certificateNewCopy: 'Use this screen to register certificates for events that have issuing enabled in UniEvent.',
    certificateFields: 'Certificate fields',
    certificateDate: 'Certificate date',
    certificateData: 'Certificate data',
    certificateHint: 'Enter the event, student, and text that will appear on the certificate.',
    selectEvent: 'Select an event',
    certificateTextPlaceholder: 'Enter the certificate text',
    certificatePreview: 'Certificate preview',
    eventNotSelected: 'Event not selected yet',
    certificateTextFallback: 'The entered text will be displayed here.',

    supportTitle: 'Support',
    lightMode: 'Light Mode',

    previewTitle: 'Preview',
    organizer: 'Organizer',
    learnMore: 'Learn More',
    aboutEvent: 'About the event',
    previewCopy: 'Our long-awaited TeckRock happens tomorrow here at the unit. An amazing rock show with a band formed by students from GPI, ADS, and GE. Free entry, with a charity collection of hygiene products.',
    getTicket: 'GET TICKET',
    notFound: 'Page not found',
    backHome: 'Back to home',
    confirm: 'Confirm',
    cancel: 'Cancel',
    tableEmpty: 'No records found',
    navigationAdmin: 'Admin navigation',
    categoryLecture: 'Lecture',
    categoryMusic: 'Music',
    categoryWorkshop: 'Workshop',
    categoryTechnology: 'Technology',
    categoryCultural: 'Cultural',
  },
};

function format(template, params = {}) {
  return Object.entries(params).reduce((value, [key, param]) => {
    return value.replaceAll(`{${key}}`, String(param));
  }, template);
}

function getInitialLanguage() {
  return localStorage.getItem(STORAGE_KEY) || 'pt';
}

export function useLanguage() {
  const [language, setLanguageState] = useState(getInitialLanguage);

  useEffect(() => {
    function handleLanguageChange(event) {
      setLanguageState(event.detail || getInitialLanguage());
    }

    window.addEventListener(LANGUAGE_EVENT, handleLanguageChange);
    return () => window.removeEventListener(LANGUAGE_EVENT, handleLanguageChange);
  }, []);

  const setLanguage = (nextLanguage) => {
    localStorage.setItem(STORAGE_KEY, nextLanguage);
    setLanguageState(nextLanguage);
    window.dispatchEvent(new CustomEvent(LANGUAGE_EVENT, { detail: nextLanguage }));
  };

  const value = useMemo(() => {
    const dictionary = dictionaries[language] || dictionaries.pt;
    const t = (key, params) => format(dictionary[key] || dictionaries.pt[key] || key, params);

    return {
      language,
      isEnglish: language === 'en',
      setLanguage,
      t,
    };
  }, [language]);

  return value;
}
